// Code generated by protoc-gen-go. DO NOT EDIT.
// source: captivated.proto

/*
Package captivated is a generated protocol buffer package.

It is generated from these files:
	captivated.proto
	macvland.proto

It has these top-level messages:
	SawClientRequest
	SawClientReply
	ClientAuthenticatedRequest
	ClientAuthenticatedReply
	ListInterfacesRequest
	ListInterfacesReply
	ListMACsRequest
	ListMACsReply
	GetInterfaceRequest
	GetInterfaceReply
	AuthoriseRequest
	AuthoriseReply
*/
package captivated

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SawClientRequest struct {
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
}

func (m *SawClientRequest) Reset()                    { *m = SawClientRequest{} }
func (m *SawClientRequest) String() string            { return proto.CompactTextString(m) }
func (*SawClientRequest) ProtoMessage()               {}
func (*SawClientRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SawClientRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type SawClientReply struct {
}

func (m *SawClientReply) Reset()                    { *m = SawClientReply{} }
func (m *SawClientReply) String() string            { return proto.CompactTextString(m) }
func (*SawClientReply) ProtoMessage()               {}
func (*SawClientReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ClientAuthenticatedRequest struct {
	Mac   string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
}

func (m *ClientAuthenticatedRequest) Reset()                    { *m = ClientAuthenticatedRequest{} }
func (m *ClientAuthenticatedRequest) String() string            { return proto.CompactTextString(m) }
func (*ClientAuthenticatedRequest) ProtoMessage()               {}
func (*ClientAuthenticatedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClientAuthenticatedRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *ClientAuthenticatedRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ClientAuthenticatedReply struct {
}

func (m *ClientAuthenticatedReply) Reset()                    { *m = ClientAuthenticatedReply{} }
func (m *ClientAuthenticatedReply) String() string            { return proto.CompactTextString(m) }
func (*ClientAuthenticatedReply) ProtoMessage()               {}
func (*ClientAuthenticatedReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*SawClientRequest)(nil), "captivated.SawClientRequest")
	proto.RegisterType((*SawClientReply)(nil), "captivated.SawClientReply")
	proto.RegisterType((*ClientAuthenticatedRequest)(nil), "captivated.ClientAuthenticatedRequest")
	proto.RegisterType((*ClientAuthenticatedReply)(nil), "captivated.ClientAuthenticatedReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Captivate service

type CaptivateClient interface {
	// Informs Captivate that a new client has appeared.
	SawClient(ctx context.Context, in *SawClientRequest, opts ...grpc.CallOption) (*SawClientReply, error)
	// Informs Captivate that a client has authenticated.
	ClientAuthenticated(ctx context.Context, in *ClientAuthenticatedRequest, opts ...grpc.CallOption) (*ClientAuthenticatedReply, error)
}

type captivateClient struct {
	cc *grpc.ClientConn
}

func NewCaptivateClient(cc *grpc.ClientConn) CaptivateClient {
	return &captivateClient{cc}
}

func (c *captivateClient) SawClient(ctx context.Context, in *SawClientRequest, opts ...grpc.CallOption) (*SawClientReply, error) {
	out := new(SawClientReply)
	err := grpc.Invoke(ctx, "/captivated.Captivate/SawClient", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captivateClient) ClientAuthenticated(ctx context.Context, in *ClientAuthenticatedRequest, opts ...grpc.CallOption) (*ClientAuthenticatedReply, error) {
	out := new(ClientAuthenticatedReply)
	err := grpc.Invoke(ctx, "/captivated.Captivate/ClientAuthenticated", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Captivate service

type CaptivateServer interface {
	// Informs Captivate that a new client has appeared.
	SawClient(context.Context, *SawClientRequest) (*SawClientReply, error)
	// Informs Captivate that a client has authenticated.
	ClientAuthenticated(context.Context, *ClientAuthenticatedRequest) (*ClientAuthenticatedReply, error)
}

func RegisterCaptivateServer(s *grpc.Server, srv CaptivateServer) {
	s.RegisterService(&_Captivate_serviceDesc, srv)
}

func _Captivate_SawClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SawClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptivateServer).SawClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/captivated.Captivate/SawClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptivateServer).SawClient(ctx, req.(*SawClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Captivate_ClientAuthenticated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientAuthenticatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptivateServer).ClientAuthenticated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/captivated.Captivate/ClientAuthenticated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptivateServer).ClientAuthenticated(ctx, req.(*ClientAuthenticatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Captivate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "captivated.Captivate",
	HandlerType: (*CaptivateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SawClient",
			Handler:    _Captivate_SawClient_Handler,
		},
		{
			MethodName: "ClientAuthenticated",
			Handler:    _Captivate_ClientAuthenticated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "captivated.proto",
}

func init() { proto.RegisterFile("captivated.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x4e, 0x2c, 0x28,
	0xc9, 0x2c, 0x4b, 0x2c, 0x49, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0xa9, 0x70, 0x09, 0x04, 0x27, 0x96, 0x3b, 0xe7, 0x64, 0xa6, 0xe6, 0x95, 0x04, 0xa5, 0x16,
	0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x70, 0x31, 0xe7, 0x26, 0x26, 0x4b, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x81, 0x98, 0x4a, 0x02, 0x5c, 0x7c, 0x48, 0xaa, 0x0a, 0x72, 0x2a, 0x95, 0x5c, 0xb8,
	0xa4, 0x20, 0x5c, 0xc7, 0xd2, 0x92, 0x8c, 0xd4, 0xbc, 0x92, 0xcc, 0x64, 0x90, 0x71, 0x38, 0x4d,
	0x10, 0x12, 0xe1, 0x62, 0x4d, 0xcd, 0x4d, 0xcc, 0xcc, 0x91, 0x60, 0x02, 0x8b, 0x41, 0x38, 0x4a,
	0x52, 0x5c, 0x12, 0x58, 0x4d, 0x29, 0xc8, 0xa9, 0x34, 0xda, 0xcd, 0xc8, 0xc5, 0xe9, 0x0c, 0x73,
	0xa8, 0x90, 0x3b, 0x17, 0x27, 0xdc, 0x05, 0x42, 0x32, 0x7a, 0x48, 0x7e, 0x42, 0x77, 0xbe, 0x94,
	0x14, 0x0e, 0x59, 0x90, 0xb3, 0x19, 0x84, 0x52, 0xb9, 0x84, 0xb1, 0x58, 0x29, 0xa4, 0x86, 0xac,
	0x09, 0xb7, 0xcf, 0xa4, 0x54, 0x08, 0xaa, 0x03, 0x5b, 0x93, 0xc4, 0x06, 0x0e, 0x6a, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0xb6, 0x71, 0x22, 0x7e, 0x01, 0x00, 0x00,
}
